name: Daily Crawler

on:
  schedule:
    - cron: '40 1 * * *'  # 每天晚上 12:10 UTC 运行
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-crawler:
    runs-on: ubuntu-22.04  # 选择运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 设置为最新 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装依赖

      - name: Run the crawler
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}  # 使用存储的网址
          USERNAME: ${{ secrets.USERNAME }}  # 使用存储的账号
          PASSWORD: ${{ secrets.PASSWORD }}  # 使用存储的密码
        run: |
          python test2.py  # 运行爬虫脚本
