name: Windows Crawler

on:
  schedule:
    - cron: '11 16 * * *'  # 每天下午 4:11 UTC 运行
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-crawler:
    runs-on: windows-latest  # 选择 Windows 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # 设置为最新 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装依赖

      - name: Run the crawler
        env:
          USERNAME: ${{ secrets.USERNAME }}  # 使用存储的账号
          PASSWORD: ${{ secrets.PASSWORD }}  # 使用存储的密码
        run: |
          python test2.py  # 运行爬虫脚本
